### ISSUE TITLE
add summary_snapshot_module

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/shiny-module-gallery#14]
Acceptance Criteria:
Get this module working in the gallery
![Screenshot from 2022-04-11 13-20-48](https://user-images.githubusercontent.com/7220713/162825260-956f9842-6e0e-4cb4-a0ea-4f3dd48612c9.png)
:

**Comment by ychae** [comment]
@andrewelamb do you have a screenshot of just the summary snapshot module? It'd be great to be able to include it in the presentation we have on Wednesday. Thanks!

**Comment by andrewelamb** [comment]
![snapshot1](https://user-images.githubusercontent.com/7220713/163046060-202eebc1-a682-44a2-b7ca-3449bd880229.jpg)
![snapshot2](https://user-images.githubusercontent.com/7220713/163046072-369a352d-8724-42ea-a37e-ae9dd1362d7c.jpg)

@ychae
