### ISSUE TITLE
add publication_status_module

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/shiny-module-gallery#15]

**Comment by andrewelamb** [comment]
@milen-sage @ychae Let's add this to sprint 7 planning.

Acceptance criteria:

Get this module working in the app
![Screenshot from 2022-04-26 07-48-36](https://user-images.githubusercontent.com/7220713/165327968-a0bb322a-b797-4ea3-8f4e-b2da653b2359.png)
:

**Comment by milen-sage** [comment]
Closing an old issue? :)

**Comment by andrewelamb** [comment]
Yeah I was doing some spring cleaning on old issues :). Any modules going forward would be from projectLive2.
